### ISSUE TITLE
projectId is undefined when passed as a config option

### ISSUE THREAD

**Issue by ehrhart** [jschnurr/botkit-middleware-dialogflow#13]
`projectId` is undefined when passed as a config option.

## How to reproduce:

```
DialogflowMiddleware({
  version: 'V2',
  projectId: 'test-project',
  keyFilename: 'keyfile.json'
});
```

## Stack trace:

```
dialogflow returned error TypeError: Cannot read property 'charCodeAt' of undefined
    at peg$parsetemplate (node_modules/google-gax/lib/path_template_parser.js:309:17)
    at Object.peg$parse [as parse] (node_modules/google-gax/lib/path_template_parser.js:640:18)
    at new PathTemplate (node_modules/google-gax/lib/path_template.js:52:47)
    at node_modules/google-gax/lib/path_template.js:139:17
    at Array.forEach (<anonymous>)
    at PathTemplate.render (node_modules/google-gax/lib/path_template.js:129:17)
    at SessionsClient.sessionPath (node_modules/dialogflow/src/v2/sessions_client.js:320:52)
    at DialogFlowAPI_V2.query (node_modules/botkit-middleware-dialogflow/src/api.js:101:25)
    at Object.middleware.receive (node_modules/botkit-middleware-dialogflow/src/botkit-middleware-dialogflow.js:39:34)
    ...
```

**Comment by jschnurr** [comment]
Resolved in v2.0.4.
