### ISSUE TITLE
Build failed with botkit-middleware-dialogflow module

### ISSUE THREAD

**Issue by khajam30** [jschnurr/botkit-middleware-dialogflow#19]
Dear Jeff and experts
I am trying to **build** myjabber bot app by adding module "botkit-middleware-dialogflow": "^2.0.4" , but it returns the below error could you please help find the cause of the issue

Thanks

4:04:35 PM (Builder) Build of "/CiscoJabber/myjabber" started.
4:04:44 PM (DIBuild) Build of "/CiscoJabber/myjabber" in progress.
4:04:45 PM (DIBuild) Service provisioning for module: '/myjabber'[INFO] Injecting source code into builder...[INFO] Source code injection finished[INFO] ------------------------------------------------------------------------
4:05:13 PM (DIBuild) > grpc@1.17.0 install /home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc> node-pre-gyp install --fallback-to-build --library=static_librarygyp ERR! configure error gyp ERR! stack Error: ENOENT: no such file or directory, open '/home/vcap/app/META-INF/resources/nodejs/aggr.pem'gyp ERR! stack at Object.fs.openSync (fs.js:646:18)gyp ERR! stack at Object.fs.readFileSync (fs.js:551:33)gyp ERR! stack at readCAFile (/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:466:15)gyp ERR! stack at download (/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:438:22)gyp ERR! stack at /home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:185:19gyp ERR! stack at /home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/mkdirp/index.js:48:26gyp ERR! stack at FSReqWrap.oncomplete (fs.js:153:5)gyp ERR! System Linux 4.15.0-39-genericgyp ERR! command "/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/bin/node" "/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--library=static_library" "--module=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node" "--module_name=grpc_node" "--module_path=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc" "--napi_version=1" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v57"gyp ERR! cwd /home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpcgyp ERR! node -v v8.9.1gyp ERR! node-gyp -v v3.6.2gyp ERR! not ok node-pre-gyp ERR! build error node-pre-gyp ERR! stack Error: Failed to execute '/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/bin/node /home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)node-pre-gyp ERR! stack at ChildProcess. (/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/node_modules/node-pre-gyp/lib/util/compile.js:83:29)node-pre-gyp ERR! stack at emitTwo (events.js:126:13)node-pre-gyp ERR! stack at ChildProcess.emit (events.js:214:7)node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:925:16)node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)node-pre-gyp ERR! System Linux 4.15.0-39-genericnode-pre-gyp ERR! command "/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/bin/node" "/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--library=static_library"node-pre-gyp ERR! cwd /home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpcnode-pre-gyp ERR! node -v v8.9.1node-pre-gyp ERR! node-pre-gyp -v v0.12.0node-pre-gyp ERR! not ok Failed to execute '/home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/bin/node /home/vcap/app/.java-buildpack/tomcat/temp/nodejsbin5846029318158714442/node-v8.9.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --library=static_library --module=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node --module_name=grpc_node --module_path=/home/vcap/app/.java-buildpack/tomcat/temp/builder/sap.nodejs/builds/build-6798269379419657313/myjabber/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc --napi_version=1 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v57' (1)npm ERR! code ELIFECYCLEnpm ERR! errno 1npm ERR! grpc@1.17.0 install: node-pre-gyp install --fallback-to-build --library=static_librarynpm ERR! Exit status 1npm ERR! npm ERR! Failed at the grpc@1.17.0 install script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.npm ERR! A complete log of this run can be found in:npm ERR! /home/vcap/app/META-INF/cache/8.9.1/.npm/_logs/2019-01-13T12_05_22_461Z-debug.log
4:05:17 PM (Builder) Build of /CiscoJabber/myjabber failed.

**Comment by khajam30** [comment]
Can anybody please help, why "botkit-middleware-dialogflow": "^2.0.4" doesnt work

**Comment by jschnurr** [comment]
botkit-middleware-dialogflow doesn't appear in the stacktrace; this looks like a different problem.  Did you check the log?
